# Generated by Django 5.1.6 on 2025-02-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('feedback', models.IntegerField()),
                ('emotion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
